//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DatVe
    {
        public string MaDatVe { get; set; }
        public string MaKhachHang { get; set; }
        public string MaVe { get; set; }
        public int SoLuong { get; set; }
        public decimal TongTien { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Ve Ve { get; set; }
    }
}
