//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgheSi
    {
        public string MaNgheSi { get; set; }
        public string MaSuKien { get; set; }
        public string TenNgheSi { get; set; }
        public string TheLoai { get; set; }
        public string QuocGia { get; set; }
    
        public virtual SuKien SuKien { get; set; }
    }
}
