//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SuKienAmNhacEntities1 : DbContext
    {
        public QL_SuKienAmNhacEntities1()
            : base("name=QL_SuKienAmNhacEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DatVe> DatVes { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<NgheSi> NgheSis { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
    }
}
