//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.DatVes = new HashSet<DatVe>();
        }

        [Required(ErrorMessage ="Ma Ve is required")]
        public string MaVe { get; set; }

        [Required(ErrorMessage ="Ma su kien is required")]
        public string MaSuKien { get; set; }

        [Required(ErrorMessage ="Loai su kien is required")]
        public string LoaiVe { get; set; }

        [Required(ErrorMessage ="Gia ve is required")]
        
        public decimal GiaVe { get; set; }

        [Required]
        public int SoLuong { get; set; }


        public string AnhVe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatVe> DatVes { get; set; }
        public virtual SuKien SuKien { get; set; }
    }
}
